[FIX] account_product_fiscal_classification: Deactivate demo data
This demo data, due to YAML load mechanism, is breaking other modules
installation.

As they are not used for tests and only added as visual aid, we
deactivate them

Example error:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/odoo/custom/src/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/openerp/modules/loading.py", line 357, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/custom/src/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/custom/src/odoo/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/odoo/custom/src/odoo/openerp/modules/module.py", line 290, in init_module_models
    obj.init(cr)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/auto/addons/report/models/report_paperformat.py", line 132, in init
    company.write({'paperformat_id': paperformat_id})
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/addons/base/res/res_company.py", line 310, in write
    return super(res_company, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 3811, in write
    self._write(old_vals)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 4066, in _write
    cr, user, todo, fields_to_recompute, context)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 4473, in _store_set_values
    result = column.get(cr, self, ids, f, SUPERUSER_ID, context=context)
  File "/opt/odoo/custom/src/odoo/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/custom/src/odoo/openerp/osv/fields.py", line 1534, in _related_read
    res[record.id] = value[self.arg[-1]]
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 5681, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/custom/src/odoo/openerp/fields.py", line 835, in __get__
    self.determine_value(record)
  File "/opt/odoo/custom/src/odoo/openerp/fields.py", line 928, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 3243, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 3312, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/custom/src/odoo/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_partner.fiscal_position_type does not exist
LINE 1: ..."."last_reconciliation_date","res_partner"."date","res_partn...
                                                             ^